# Generated by Django 4.1.13 on 2024-05-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductorDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dependency', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('type_producer', models.CharField(choices=[('ALCALDIA', 'Alcaldía'), ('INVIAS', 'INVIAS'), ('CENTROS_SALUD', 'Centros de salud'), ('FISCALIA', 'Fiscalía'), ('CAMARA_COMERCIO', 'Cámara de Comercio'), ('ASOMUNICIPIOS', 'Asomunicipios'), ('ESTACION_POLICIA', 'Estación de Policía'), ('ESTACION_BOMBEROS', 'Estación de bomberos'), ('EMPRESAS_SERVICIO_PUBLICO', 'Empresas de servicios públicos'), ('CORPONOR', 'CORPONOR'), ('UNIDAD_GESTION_RIESGO', 'Unidad de Gestión del Riesgo')], max_length=50)),
                ('municipality', models.CharField(choices=[('ABREGO', 'Abrego'), ('OCANA', 'Ocaña'), ('EL_CARMEN', 'El Carmen'), ('CONVENCION', 'Convención'), ('TEORAMA', 'Teorama'), ('SAN_CALIXTO', 'San Calixto'), ('HACARI', 'Hacarí'), ('LA_PLAYA_DE_BELEN', 'La Playa de Belén'), ('EL_TARRA', 'El Tarra'), ('TIBU', 'Tibú'), ('SARDINATA', 'Sardinata')], max_length=50)),
            ],
        ),
    ]
